# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

- job: SourceCodeScanningDockerLatest
  pool:
    vmImage: 'ubuntu-latest'
    
  container:
    image: checkpoint/shiftleft:0.0.31
    options: --interactive
  steps:
  - bash: |
        git clone https://github.com/chkp-ecarbon/demo-app
        shiftleft code-scan -t 900 -s ./demo-app
    env:
      #Map secret variables to environment variables
      CHKP_CLOUDGUARD_ID: $(CHKP_CLOUDGUARD_ID)
      CHKP_CLOUDGUARD_SECRET: $(CHKP_CLOUDGUARD_SECRET)
    displayName: Running Source Code scan
