

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
 Code-Scan:
       runs-on: ubuntu-latest
       steps:
      
   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
  
   # Runs a code scan
        - name: Run shiftleft code scan
          env:
           CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
           CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
          run: |
           chmod +x ./shiftleft
           git clone https://github.com/chkp-ecarbon/demo-app.git
           ./shiftleft code-scan -s ./demo-app
           
 Terraform-Scan:        
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v2
            
   # Runs IAC Test for Terraform
           - name: Terraform-Scan
             env:
              CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
              CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
             run: | 
               git clone https://github.com/chkp-ecarbon/demo-app.git
               chmod +x ./shiftleft
               ./shiftleft iac-assessment -r -64 -p ./terraform
               
 Docker-Scan:
           runs-on: ubuntu-latest
           steps:
             - uses: actions/checkout@v2
   # Run a container image scan
             - name: Docker-Scan
               env:
                 CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
                 CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
               run: |
                 git clone https://github.com/chkp-ecarbon/demo-app.git
                 docker build -t carboncp/myapp ./demo-app
                 docker save -o myapp.tar /carboncp/myapp
                 chmod +x ./shiftleft
                 ./shiftleft image-scan -i myapp.tar
         
